from json_tools import json_to_dict

"""
This file can be used to get specific
CoVid-19 data from any and all available
countries.
"""


class CoVidData:

    def __init__(self, 
                 total_cases=0,
                 new_cases=1,
                 total_deaths=2,
                 new_deaths=3,
                 total_recovered=4,
                 new_recovered=5,
                 active_cases=6,
                 serious_critical=7,
                 total_cases_per_million=8,
                 deaths_per_million=9,
                 total_tests=10,
                 test_per_million=11,
                 population=12):
        self.total_cases = total_cases
        self.new_cases = new_cases
        self.total_deaths = total_deaths
        self.new_deaths = new_deaths
        self.total_recovered = total_recovered
        self.new_recovered = new_recovered
        self.active_cases = active_cases
        self.serious_critical = serious_critical
        self.total_cases_per_million = total_cases_per_million
        self.deaths_per_million = deaths_per_million
        self.total_tests = total_tests
        self.test_per_million = test_per_million
        self.population = population


class Countries:

    def __init__(self,
                 usa='USA',
                 india='India',
                 brazil='Brazil',
                 russia='Russia',
                 france='France',
                 uk='UK',
                 turkey='Turkey',
                 argentina='Argentina',
                 colombia='Colombia',
                 spain='Spain',
                 italy='Italy',
                 iran='Iran',
                 germany='Germany',
                 indonesia='Indonesia',
                 poland='Poland',
                 mexico='Mexico',
                 south_africa='South Africa',
                 ukraine='Ukraine',
                 peru='Peru',
                 netherlands='Netherlands',
                 czechia='Czechia',
                 iraq='Iraq',
                 chile='Chile',
                 philippines='Philippines',
                 canada='Canada',
                 bangladesh='Bangladesh',
                 malaysia='Malaysia',
                 belgium='Belgium',
                 sweden='Sweden',
                 romania='Romania',
                 pakistan='Pakistan',
                 portugal='Portugal',
                 japan='Japan',
                 israel='Israel',
                 hungary='Hungary',
                 jordan='Jordan',
                 serbia='Serbia',
                 switzerland='Switzerland',
                 nepal='Nepal',
                 uae='UAE',
                 austria='Austria',
                 morocco='Morocco',
                 thailand='Thailand',
                 tunisia='Tunisia',
                 kazakhstan='Kazakhstan',
                 lebanon='Lebanon',
                 saudi_arabia='Saudi Arabia',
                 greece='Greece',
                 ecuador='Ecuador',
                 bolivia='Bolivia',
                 paraguay='Paraguay',
                 belarus='Belarus',
                 panama='Panama',
                 bulgaria='Bulgaria',
                 georgia='Georgia',
                 costa_rica='Costa Rica',
                 cuba='Cuba',
                 kuwait='Kuwait',
                 slovakia='Slovakia',
                 uruguay='Uruguay',
                 guatemala='Guatemala',
                 croatia='Croatia',
                 azerbaijan='Azerbaijan',
                 dominican_republic='Dominican Republic',
                 denmark='Denmark',
                 palestine='Palestine',
                 sri_lanka='Sri Lanka',
                 venezuela='Venezuela',
                 myanmar='Myanmar',
                 ireland='Ireland',
                 oman='Oman',
                 honduras='Honduras',
                 egypt='Egypt',
                 lithuania='Lithuania',
                 ethiopia='Ethiopia',
                 bahrain='Bahrain',
                 moldova='Moldova',
                 slovenia='Slovenia',
                 libya='Libya',
                 armenia='Armenia',
                 qatar='Qatar',
                 bosnia_and_herzegovina='Bosnia and Herzegovina',
                 kenya='Kenya',
                 s_korea='S. Korea',
                 zambia='Zambia',
                 nigeria='Nigeria',
                 algeria='Algeria',
                 mongolia='Mongolia',
                 kyrgyzstan='Kyrgyzstan',
                 vietnam='Vietnam',
                 north_macedonia='North Macedonia',
                 afghanistan='Afghanistan',
                 latvia='Latvia',
                 norway='Norway',
                 estonia='Estonia',
                 albania='Albania',
                 uzbekistan='Uzbekistan',
                 mozambique='Mozambique',
                 namibia='Namibia',
                 zimbabwe='Zimbabwe',
                 finland='Finland',
                 botswana='Botswana',
                 ghana='Ghana',
                 cyprus='Cyprus',
                 montenegro='Montenegro',
                 uganda='Uganda',
                 el_salvador='El Salvador',
                 cameroon='Cameroon',
                 cambodia='Cambodia',
                 maldives='Maldives',
                 luxembourg='Luxembourg',
                 rwanda='Rwanda',
                 singapore='Singapore',
                 senegal='Senegal',
                 jamaica='Jamaica',
                 malawi='Malawi',
                 ivory_coast='Ivory Coast',
                 drc='DRC',
                 angola='Angola',
                 madagascar='Madagascar',
                 trinidad_and_tobago='Trinidad and Tobago',
                 runion='Runion',
                 sudan='Sudan',
                 australia='Australia',
                 malta='Malta',
                 cabo_verde='Cabo Verde',
                 fiji='Fiji',
                 french_guiana='French Guiana',
                 eswatini='Eswatini',
                 mauritania='Mauritania',
                 syria='Syria',
                 guinea='Guinea',
                 suriname='Suriname',
                 gabon='Gabon',
                 guyana='Guyana',
                 haiti='Haiti',
                 french_polynesia='French Polynesia',
                 guadeloupe='Guadeloupe',
                 mayotte='Mayotte',
                 martinique='Martinique',
                 seychelles='Seychelles',
                 papua_new_guinea='Papua New Guinea',
                 togo='Togo',
                 taiwan='Taiwan',
                 somalia='Somalia',
                 tajikistan='Tajikistan',
                 bahamas='Bahamas',
                 andorra='Andorra',
                 mali='Mali',
                 belize='Belize',
                 curaao='Curaao',
                 lesotho='Lesotho',
                 burkina_faso='Burkina Faso',
                 congo='Congo',
                 hong_kong='Hong Kong',
                 aruba='Aruba',
                 djibouti='Djibouti',
                 south_sudan='South Sudan',
                 timor_leste='Timor-Leste',
                 nicaragua='Nicaragua',
                 channel_islands='Channel Islands',
                 equatorial_guinea='Equatorial Guinea',
                 benin='Benin',
                 iceland='Iceland',
                 gambia='Gambia',
                 burundi='Burundi',
                 car='CAR',
                 yemen='Yemen',
                 laos='Laos',
                 eritrea='Eritrea',
                 sierra_leone='Sierra Leone',
                 niger='Niger',
                 saint_lucia='Saint Lucia',
                 liberia='Liberia',
                 san_marino='San Marino',
                 gibraltar='Gibraltar',
                 chad='Chad',
                 isle_of_man='Isle of Man',
                 guinea_bissau='Guinea-Bissau',
                 barbados='Barbados',
                 comoros='Comoros',
                 mauritius='Mauritius',
                 liechtenstein='Liechtenstein',
                 monaco='Monaco',
                 new_zealand='New Zealand',
                 sint_maarten='Sint Maarten',
                 saint_martin='Saint Martin',
                 bermuda='Bermuda',
                 bhutan='Bhutan',
                 british_virgin_islands='British Virgin Islands',
                 turks_and_caicos='Turks and Caicos',
                 sao_tome_and_principe='Sao Tome and Principe',
                 st_vincent_grenadines='St. Vincent Grenadines',
                 caribbean_netherlands='Caribbean Netherlands',
                 antigua_and_barbuda='Antigua and Barbuda',
                 st_barth='St. Barth',
                 tanzania='Tanzania',
                 faeroe_islands='Faeroe Islands',
                 diamond_princess='Diamond Princess',
                 cayman_islands='Cayman Islands',
                 saint_kitts_and_nevis='Saint Kitts and Nevis',
                 wallis_and_futuna='Wallis and Futuna',
                 brunei='Brunei',
                 dominica='Dominica',
                 grenada='Grenada',
                 new_caledonia='New Caledonia',
                 greenland='Greenland',
                 anguilla='Anguilla',
                 falkland_islands='Falkland Islands',
                 macao='Macao',
                 saint_pierre_miquelon='Saint Pierre Miquelon',
                 vatican_city='Vatican City',
                 montserrat='Montserrat',
                 solomon_islands='Solomon Islands',
                 western_sahara='Western Sahara',
                 ms_zaandam='MS Zaandam',
                 vanuatu='Vanuatu',
                 marshall_islands='Marshall Islands',
                 samoa='Samoa',
                 saint_helena='Saint Helena',
                 micronesia='Micronesia',
                 china='China'):
        self.usa = usa
        self.india = india
        self.brazil = brazil
        self.russia = russia
        self.france = france
        self.uk = uk
        self.turkey = turkey
        self.argentina = argentina
        self.colombia = colombia
        self.spain = spain
        self.italy = italy
        self.iran = iran
        self.germany = germany
        self.indonesia = indonesia
        self.poland = poland
        self.mexico = mexico
        self.south_africa = south_africa
        self.ukraine = ukraine
        self.peru = peru
        self.netherlands = netherlands
        self.czechia = czechia
        self.iraq = iraq
        self.chile = chile
        self.philippines = philippines
        self.canada = canada
        self.bangladesh = bangladesh
        self.malaysia = malaysia
        self.belgium = belgium
        self.sweden = sweden
        self.romania = romania
        self.pakistan = pakistan
        self.portugal = portugal
        self.japan = japan
        self.israel = israel
        self.hungary = hungary
        self.jordan = jordan
        self.serbia = serbia
        self.switzerland = switzerland
        self.nepal = nepal
        self.uae = uae
        self.austria = austria
        self.morocco = morocco
        self.thailand = thailand
        self.tunisia = tunisia
        self.kazakhstan = kazakhstan
        self.lebanon = lebanon
        self.saudi_arabia = saudi_arabia
        self.greece = greece
        self.ecuador = ecuador
        self.bolivia = bolivia
        self.paraguay = paraguay
        self.belarus = belarus
        self.panama = panama
        self.bulgaria = bulgaria
        self.georgia = georgia
        self.costa_rica = costa_rica
        self.cuba = cuba
        self.kuwait = kuwait
        self.slovakia = slovakia
        self.uruguay = uruguay
        self.guatemala = guatemala
        self.croatia = croatia
        self.azerbaijan = azerbaijan
        self.dominican_republic = dominican_republic
        self.denmark = denmark
        self.palestine = palestine
        self.sri_lanka = sri_lanka
        self.venezuela = venezuela
        self.myanmar = myanmar
        self.ireland = ireland
        self.oman = oman
        self.honduras = honduras
        self.egypt = egypt
        self.lithuania = lithuania
        self.ethiopia = ethiopia
        self.bahrain = bahrain
        self.moldova = moldova
        self.slovenia = slovenia
        self.libya = libya
        self.armenia = armenia
        self.qatar = qatar
        self.bosnia_and_herzegovina = bosnia_and_herzegovina
        self.kenya = kenya
        self.s_korea = s_korea
        self.zambia = zambia
        self.nigeria = nigeria
        self.algeria = algeria
        self.mongolia = mongolia
        self.kyrgyzstan = kyrgyzstan
        self.vietnam = vietnam
        self.north_macedonia = north_macedonia
        self.afghanistan = afghanistan
        self.latvia = latvia
        self.norway = norway
        self.estonia = estonia
        self.albania = albania
        self.uzbekistan = uzbekistan
        self.mozambique = mozambique
        self.namibia = namibia
        self.zimbabwe = zimbabwe
        self.finland = finland
        self.botswana = botswana
        self.ghana = ghana
        self.cyprus = cyprus
        self.montenegro = montenegro
        self.uganda = uganda
        self.el_salvador = el_salvador
        self.cameroon = cameroon
        self.cambodia = cambodia
        self.maldives = maldives
        self.luxembourg = luxembourg
        self.rwanda = rwanda
        self.singapore = singapore
        self.senegal = senegal
        self.jamaica = jamaica
        self.malawi = malawi
        self.ivory_coast = ivory_coast
        self.drc = drc
        self.angola = angola
        self.madagascar = madagascar
        self.trinidad_and_tobago = trinidad_and_tobago
        self.sudan = sudan
        self.australia = australia
        self.malta = malta
        self.cabo_verde = cabo_verde
        self.fiji = fiji
        self.french_guiana = french_guiana
        self.eswatini = eswatini
        self.mauritania = mauritania
        self.syria = syria
        self.guinea = guinea
        self.suriname = suriname
        self.gabon = gabon
        self.guyana = guyana
        self.haiti = haiti
        self.french_polynesia = french_polynesia
        self.guadeloupe = guadeloupe
        self.mayotte = mayotte
        self.martinique = martinique
        self.seychelles = seychelles
        self.papua_new_guinea = papua_new_guinea
        self.togo = togo
        self.taiwan = taiwan
        self.somalia = somalia
        self.tajikistan = tajikistan
        self.bahamas = bahamas
        self.andorra = andorra
        self.mali = malaysia
        self.belize = belize
        self.curaao = curaao
        self.lesotho = lesotho
        self.burkina_faso = burkina_faso
        self.congo = congo
        self.hong_kong = hong_kong
        self.aruba = aruba
        self.djibouti = djibouti
        self.south_sudan = south_sudan
        self.timor_leste = timor_leste
        self.nicaragua = nicaragua
        self.channel_islands = channel_islands
        self.equatorial_guinea = equatorial_guinea
        self.benin = benin
        self.iceland = iceland
        self.gambia = gambia
        self.burundi = burundi
        self.car = car
        self.yemen = yemen
        self.laos = laos
        self.eritrea = eritrea
        self.sierra_leone = sierra_leone
        self.niger = niger
        self.saint_lucia = saint_lucia
        self.liberia = liberia
        self.san_marino = san_marino
        self.gibraltar = gibraltar
        self.chad = chad
        self.isle_of_man = isle_of_man
        self.guinea_bissau = guinea_bissau
        self.barbados = barbados
        self.comoros = comoros
        self.mauritius = mauritius
        self.liechtenstein = liechtenstein
        self.monaco = monaco
        self.new_zealand = new_zealand
        self.sint_maarten = sint_maarten
        self.saint_martin = saint_martin
        self.bermuda = bermuda
        self.bhutan = bhutan
        self.british_virgin_islands = british_virgin_islands
        self.turks_and_caicos = turks_and_caicos
        self.sao_tome_and_principe = sao_tome_and_principe
        self.st_vincent_grenadines = st_vincent_grenadines
        self.caribbean_netherlands = caribbean_netherlands
        self.antigua_and_barbuda = antigua_and_barbuda
        self.st_barth = st_barth
        self.tanzania = tanzania
        self.faeroe_islands = faeroe_islands
        self.diamond_princess = diamond_princess
        self.cayman_islands = cayman_islands
        self.saint_kitts_and_nevis = saint_kitts_and_nevis
        self.wallis_and_futuna = wallis_and_futuna
        self.brunei = brunei
        self.dominica = dominican_republic
        self.grenada = grenada
        self.new_caledonia = new_caledonia
        self.greenland = greenland
        self.anguilla = anguilla
        self.falkland_islands = falkland_islands
        self.macao = macao
        self.saint_pierre_miquelon = saint_pierre_miquelon
        self.vatican_city = vatican_city
        self.montserrat = montserrat
        self.solomon_islands = solomon_islands
        self.western_sahara = western_sahara
        self.ms_zaandam = ms_zaandam
        self.vanuatu = vanuatu
        self.marshall_islands = marshall_islands
        self.samoa = samoa
        self.saint_helena = saint_helena
        self.micronesia = micronesia
        self.china = china


# Create a data_points class object for each country's CoVid-19 data
data_points = CoVidData()
covid_countries = Countries()


def get_framework_datapoint(country, data):

    framework = json_to_dict('CoVid-Data.json')

    variable = framework[country][data]

    return variable


if __name__ == '__main__':

    # This example is just a test...
    data = get_framework_datapoint(covid_countries.usa, data_points.population)
    print(data)
